apiVersion: multicluster.x-k8s.io/v1alpha1
kind: Work
metadata:
  name: work-sample
spec:
  workload:
    manifests:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cm1
        namespace: default
